project:
  type: book

book:
  title: "Hub Decoupled Architecture"
  author: "Gary Newport"
  favicon: coverG.png
  date: "21/04/2026"
  sidebar: 
    background: "#F5F5F5"
    logo: covereGB.png
    search: true
  chapters:
    - index.qmd
    - Book/Executive Summary & Objectives.qmd
    - Book/Current State Assessment.qmd
    - Book/Proposed Target Architecture.qmd
    - Book/Detailed Design & Implementation.qmd
    - Book/Transition & Rollout Plan.qmd
    - Book/Operations & Maintenance.qmd

#    - Book/architectural-constraints/index.qmd
#    - Book/system-scope-and-context/index.qmd
#    - part: Book/building-block-view/building-block-view/index.qmd
#      chapters:
#        - Book/building-block-view/azure-function-detail/index.qmd
#        - Book/building-block-view/cosmos-db-component/index.qmd
#        - Book/building-block-view/domain-logic-component/index.qmd
#        - Book/building-block-view/security-component/index.qmd
#    - Book/solution-strategy/index.qmd
#    - Book/runtime-view/index.qmd
#    - Book/deployment-view/index.qmd

format:
  html:
    theme:
      - cosmo
      - brand
#  pdf:
#    documentclass: scrreprt


#diagram:
#  engine:
#    plantuml:
#      execpath: "C:/Plantuml/plantuml.bat"

filters:
  - plantuml-diagram
